== GitHub Wiki Workshop

This project is the base for a workshop to explain the essential functions of GitHub Wikis.

For more information go to: https://github.com/Gepardec/github-wiki-training/wiki[]

=== Example Code

The code in this repository is just a simple "Hello World!"-Application which only has the purpose of not leaving the repository empty.

=== Prerequisites for the workshop

To execute some of the examples and try things out on your own, there are two prerequisites:

1. a GitHub account (https://github.com/join?ref_cta=Sign%20up[Join GitHub · GitHub])
2. an working git installation on your computer (https://git-scm.com/download[Git - Downloads])

=== Workshop language

All the workshop materials are written in german.If you are interested in information in english please open an issue and let us know.

== Authors

* **Christian Salmhofer** - *Initial work* - https://github.com/csalmhof[csalmhof]

== License

This project is licensed under the MIT License - see the LICENSE.md file for details
